{% set version = '0.6.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-profilemodel
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/profileModel_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/profileModel/profileModel_{{ version }}.tar.gz
  sha256: a829ceec29c817d6d15947b818e28f9cf5a188a231b9b5d0a75018388887087b

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS, gnm
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('profileModel')"           # [not win]
    - "\"%R%\" -e \"library('profileModel')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ikosmidis/profileModel
  license: GPL (>= 2)
  summary: Provides tools that can be used to calculate, evaluate, plot and use for inference
    the profiles of *arbitrary* inference functions for *arbitrary* 'glm'-like fitted
    models with linear predictors. More information on the methods that are implemented
    can be found in Kosmidis (2008) <https://www.r-project.org/doc/Rnews/Rnews_2008-2.pdf>.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: profileModel
# Type: Package
# Title: Profiling Inference Functions for Various Model Classes
# Version: 0.6.0
# Authors@R: person(given = "Ioannis", family = "Kosmidis", role = c("aut", "cre"), email = "ioannis.kosmidis@warwick.ac.uk", comment = c(ORCID = "0000-0003-1556-0302"))
# URL: https://github.com/ikosmidis/profileModel
# BugReports: https://github.com/ikosmidis/profileModel/issues
# Description: Provides tools that can be used to calculate, evaluate, plot and use for inference the profiles of *arbitrary* inference functions for *arbitrary* 'glm'-like fitted models with linear predictors. More information on the methods that are implemented can be found in Kosmidis (2008) <https://www.r-project.org/doc/Rnews/Rnews_2008-2.pdf>.
# License: GPL (>= 2)
# Depends: R (>= 2.6.0)
# Suggests: MASS, gnm
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-04-03 09:43:32 UTC; yiannis
# Author: Ioannis Kosmidis [aut, cre] (<https://orcid.org/0000-0003-1556-0302>)
# Maintainer: Ioannis Kosmidis <ioannis.kosmidis@warwick.ac.uk>
# Repository: CRAN
# Date/Publication: 2019-04-03 11:40:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
