travis:
  secure:
    BINSTAR_TOKEN: fTm0zR//jtaYfzmKG2F+Xz3ByLq5utmscQ//5XIaxrsU5MZmFDW6pg04RCx1uBwU9KNlBW97IyOryWRJ1s7qtL1fLCZkHHDZpKH5pQR2aJrdUiUOugONUkPQWR7IfononI0KtaM2EWfaB3qTCKSW8SUDS5Y63qvpipS/M66809wfWZiYkOFppV1h9Syi2El4OteYkF6wuhQJR5zsAulk/6a0EEVeiqRa1wP7EOIX4fip/u20pNXtQkktIJ/uEUi9jh1MoiyYL8gX7ag4NqhkJ6xKnXVY/2sjqaeslgYPPzDeddTYRA7tV39OM2Ay41GlmnJY8vgsIApqBJxwsUsoK5WG3JobB3yOf98fbcWkBEdx5fzrDWD49ayyq9xmfoye41OFFvTgi6UswwK+3lof2CqVmK+LEN5dULBQtLTOQwXxsWR6+/bGFv88SYr2N+aspE47coOPp8CnsBmZlY/RjAgqS+xrCMy8+i5tgoUf0BVWPtZAcY5sSUGOYWEgGGoAS5ia4VQyNM6Hx+cVQgPC9vPCUei89MscRPKTVq7+L/6DydNPW5PUmQfVD6C3ingoYPeeAPD+x8tOz6JjGS/Gaws6G3OM3a70hd73Pazm4uRqaiZSZOzZJcu926Zc99peoOnDu26XIVyNfD0qApmfGov2SsQb8x1cj+tyAyhbNrE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
