travis:
  secure:
    BINSTAR_TOKEN: kacJ645C83izKkNFzs5RrHCpOXbIY1N3IbLKBMCF0NSrOsRnAyaGQ62YkJcSWsLxFVAoRWvoi2uGbtO7sP0ii3Z7KlMYT32gKsqdTPXx7ZZxIgXieKJSxjwHYRWrefe3E7Vk86fqhYBuo+YQZ/nf43kmAVOGjlUWqQj94TK6MAb7YHqRDFAJpsg+cDTdzv6OLMS+6tqOUDtrD4Sjj/sJ30SPz030/cjvp2VUX1i06vjnp7lGsT+rPU0Cd68VtifUfNQv7J/1hzjQm0t8mYuuBB+V0vRlvanItlcn/p5nO3mWdLesyWiOLhjgpZz9o9yD5ILYX1OlbTgUzHlhy2hKGRFMmmfGMl9mxbWy4biDtMPG/RHOxJSRI0B+DfU11cRyINoBciR/aioUroeDldXbxmhsXtrdw2r+B/RrTEXxl7KRvzs2Wh5pZLKCTih2i8jZYwaRDHF7LAmTyJbYCPdmXxtVoAoOwpYCTu2HgA06UyP13E9plmdzN/0atlMdFKgSO2QfYorN3heoaWVfw9XCK4fbwObOjTjKKyoiRMwMalcmT1ePVikb53Q/TZAH1/1P5yTiMRp7rxHTPBnGdytbdPBlYT9FWpTJfwN2yV8gI6pVuUiLUYmWDuLfQoPYVW8YPcud1+o6NlGEjDiFR7ApshxhQPYvVa0KVf9+oep1JKc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
